version: '4.0'

services:
    product-service:
        container_name: product-service
        build: product/
        ports:
            - "8080:8080"

    price-service:
        container_name: price-service
        build: price/
        ports:
            - "8081"

    jaeger-service:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger-service
        ports:
            - "16686:16686"
            - "14250"

    collector:
        image: otel/opentelemetry-collector:0.72.0
        container_name: collector
        command: [ "--config=/etc/otel-collector-config.yml" ]
        volumes:
            - ./otel-config.yml:/etc/otel-collector-config.yml
        ports:
            - "4317:4317"
        depends_on:
            - jaeger-service