
server:
    port: 8081
spring:
    application:
        name: price-service
    sleuth:
        otel:
            config:
                trace-id-ratio-based: 1.0
            exporter:
                otlp:
                    endpoint: http://collector:4317
